import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Nav from "../components/nav";
import Link from "next/link";
import Cards from "../components/cards";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jolfe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`bg-white color-white w-screen m-auto h-screen pb-3`}>
        <div>
          <Link href="/home"> </Link>
        </div>
        <div className={`w-full m-auto pt-8 bg-black`}> Socials </div>
        <div className={`w-full m-auto  pr-8 bg-black font-white`}>
          <Nav />
        </div>
        <div className="bg-white">
          <Cards
            title="title"
            description="description"
            image="image"
            link="link"
          />
        </div>
      </main>
    </>
  );
}
